# This is the workflow that will build and push the Docker Image into a Docker Hub
name: CD for Assignment 3

# Workflow is triggered manually (workflow dispatch)
on:
  push:
  workflow_dispatch:
  # Must input your DockerHub username and password before triggering
    inputs:
      DOCKERHUB_USERNAME:
        description: DockerHub Username
        type: string
        default: ''
        required: true
      
      DOCKERHUB_TOKEN:
        description: DockerHub Password
        type: string
        default: ''
        required: true

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.events.inputs.DOCKERHUB_USERNAME }}
          password: ${{ github.events.inputs.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ github.events.inputs.DOCKERHUB_USERNAME }}/weeds:latest
