# This is a basic workflow to help you get started with Actions

name: CI for Assignment 3

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Chekout repository
        uses: actions/checkout@v3
      # Install Most recent version of python
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.2'
      # Install all requirements for the web app
      - name: Install Requirements
        run: pip install -r requirements.txt
      # Check if there's any migrations to make
      - name: Make Migrations
        run: python in_the_weeds/manage.py makemigrations
      # Make said migrations
      - name: Migrate
        run: python in_the_weeds/manage.py migrate
      # Test if there's any issues to run the app via System Check
      - name: Test the App
        run: python in_the_weeds/manage.py test
       # Check to make sure it's deployment ready
      - name: Check for Deployment
        run: python in_the_weeds/manage.py check --deploy 
        

      
                  
