# This is a basic workflow to help you get started with Actions

name: CI for Assignment 3

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "feature/info-page" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Chekout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.2'

      - name: Install Requirements
        run: pip install -r requirements.txt
      
      - name: Make Migrations
        run: python in_the_weeds/manage.py makemigrations

      - name: Migrate
        run: python in_the_weeds/manage.py migrate

      - name: Run the app
        run: python in_the_weeds/manage.py runserver

      - name: Run the app
        run: |
          PID=$!
          sleep 20
          kill $PID
                  
